development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: angular-rails-starter_development
  pool:     5
  username: user
  password: 
  template: template0

  
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: angular-rails-starter_test
  pool:     5
  username: user
  password: 
  template: template0

